export enum FinancePageViewState {
  MAIN,
  INVOICES,
  VIEW_INVOICES,
  INVOICE_DETAIL,
  GENERATE_INVOICES_PARAMETERS,
  GENERATE_INVOICES_RESULTS,
  PAYMENTS,
  VIEW_PAYMENTS,
  PAYMENT_DETAIL,
  GENERATE_STATEMENTS_PARAMETERS,
  VIEW_STATEMENT,
}

export enum ClientPageViewState {
  MAIN,
  VIEW,
  CLIENT_DETAIL,
}
