export enum FormFieldType {
  INPUT_GENERAL,
  INPUT_DECIMAL_NUMBER,
  INPUT_WHOLE_NUMBER,
  SELECT,
  MULTI_SELECT,
  RADIO,
  CHECKBOX,
  PASSWORD,
  FIELD_GROUP_TITLE,
  OPT_OUT,
  SLIDE_TOGGLE,
}

export enum EntityType {
  SOLE_PROPRIETOR = 1,
  REGISTERED_ENTITY = 2,
}
